### ISSUE TITLE
Är detta den nyaste versionen av spelet?

### ISSUE THREAD

**Issue by AdamJonsson** [ShadowNinja44/Death-by-Darkness#1]

**Comment by ghost** [comment]
Jag är ganska säker på att detta är en relativt tidig version utan mycket implementerat. Jag pushar en zip-fil med vad jag tror är senaste versionen till master-branchen.

**Comment by AdamJonsson** [comment]
Nice, tack =)

**Comment by ghost** [comment]
Push-fil för stor, skickar via messenger.

**Comment by ghost** [comment]
För stor för messenger, lägger den i gemensam dropbox-mapp.
